apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: desafio-app
  annotations:
    iam.gke.io/gcp-service-account: desafio-app-gke-prd-node-sa@PROJECT_ID.iam.gserviceaccount.com

